server:
  port: 9000

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://localhost:8081
        predicates:
        - Path=/user/**
        filters:
        - AuthenticationFilter

      - id: product-service
        uri: http://localhost:8082
        predicates:
        - Path=/product/**
        filters:
        - AuthenticationFilter

      - id: livestock-service
        uri: http://localhost:8083
        predicates:
        - Path=/livestock/**

      - id: inventory-service
        uri: http://localhost:8084
        predicates:
        - Path=/inventory/**

      - id: customer-service
        uri: http://localhost:8085
        predicates:
        - Path=/customer/**

      - id: billing-service
        uri: http://localhost:8086
        predicates:
        - Path=/billing/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway